POST http://localhost:8080/kafka-edu/produce
Content-Type: application/json

{
  "instanceId": "string",
  "siebelId": "string",
  "task": {
    "id": "string",
    "requestId": "string",
    "type": "string",
    "status": "string",
    "lifeTime": "string",
    "description": "string"
  },
  "documents": [
    {
      "id": "string",
      "documentType": "string"
    },
    {
      "id": "string",
      "documentType": "string"
    }
  ]
}