POST http://localhost:8080/kafka-edu/produce
Content-Type: application/json

{
  "instanceId": "QWE-1987",
  "siebelId": "ASB-1112",
  "task": {
    "id": "76543887251",
    "requestId": "asd91kmnc836KKs82Tas",
    "type": "payrollL",
    "status": "NEW",
    "lifeTime": "323445666",
    "description": "For testing kafka"
  },
  "documents": [
    {
      "id": "776",
      "documentType": "PDF"
    },
    {
      "id": "882",
      "documentType": "PDF"
    }
  ]
}