spring:
  kafka:
    consumer:
      bootstrap-servers: ${BOOTSTRAP_SERVERS:localhost:29092}
      group-id: ${CONSUMER_GROUP_ID:document-sign}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

paperless:
  topic:
    json: paperless.kafka.edu
    avro: paperless.kafka.edu.avro
